on:
  push:
    branches:
      - master
name: build and release-please
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: commit
        run: |-
          git checkout -b build-pr
          git config --global user.name "actions-bot"
          git add dist/
          git diff-index --quiet HEAD || git commit -m "chore: build dist get-gke-credentials"
          git push --set-upstream origin build-pr
          gh pr create --title "chore: build dist" --body "build dist" --base main --label automated-pr
  # release-please-pr:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: google-github-actions/release-please-action@main
  #       with:
  #         token: ${{ secrets.ACTIONS_BOT_TOKEN }}
  #         release-type: node
  #         fork: true
  #         package-name: get-gke-credentials
  #         path: get-gke-credentials
  #         monorepo-tags: get-gke-credentials
  #         command: release-pr
  # release-please-release:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: google-github-actions/release-please-action@main
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         release-type: node
  #         package-name: get-gke-credentials
  #         path: get-gke-credentials
  #         monorepo-tags: get-gke-credentials
  #         command: github-release
