on:
  push:
    branches:
      - main
name: build and release-please
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git pull
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: commit
        run: |-
          CURRENT_HASH=$(git rev-parse HEAD)
          LAST_BUILD_HASH=$(git log --author=google-github-actions-bot -1 --pretty=format:"%H")
          echo ${LAST_BUILD_HASH}
          DIFF=""
          git config --global user.name "actions-bot"
          git config user.email 'github-actions-bot@google.com'
          git add dist/
          git diff-index --quiet HEAD || git commit -m "chore: build dist get-gke-credentials"
          if [ -z "$LAST_BUILD_HASH" ]
          then
                echo "Unable to find last commit by bot, skipping diff gen"
          else
                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
                echo $DIFF
          fi
          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
          echo "DIFF=${DIFF}" >> $GITHUB_ENV
          echo ${{env.DIFF}}
      - name: compute diff
        run: |-
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          commit-message: Build dist
          author: "actions-bot <github-actions-bot@google.com>"
          title: Build dist
          body: |
            Build dist ${{env.DIFF}}
          labels: automated pr
          branch: create-pull-request/build-dist
          delete-branch: true
          push-to-fork: google-github-actions-bot/get-gke-credentials
  # release-please-pr:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: google-github-actions/release-please-action@main
  #       with:
  #         token: ${{ secrets.ACTIONS_BOT_TOKEN }}
  #         release-type: node
  #         fork: true
  #         package-name: get-gke-credentials
  #         path: get-gke-credentials
  #         monorepo-tags: get-gke-credentials
  #         command: release-pr
  # release-please-release:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: google-github-actions/release-please-action@main
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         release-type: node
  #         package-name: get-gke-credentials
  #         path: get-gke-credentials
  #         monorepo-tags: get-gke-credentials
  #         command: github-release
